# to define the GitHub workflows for GitHub actions
name: Release Charts

on:
  push:
    branches:
      # trigger the workflow on push to the main branch
      - main

jobs:
  release:
    permissions:
      # It will have the write permission
      contents: write  
    # it runs on ubuntu latest agent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      # to run the chart-releaser action
      # go ahead and then build the package like helm package command
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"